version: 2 # will always be v2 of circle ci
jobs:
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
  build:
    docker:
      - image: circleci/node:lts # this will almost always be the case unless the project needs a custom docker file
    steps:
      - checkout # step in ci that gets code from GitHub
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build React app
          command: npm run build
    deploy:
      docker:
        - image: circleci/node:lts
      steps:
        - checkout # step in ci that gets code from GitHub
        - run:
            name: Deploy
            command: 'echo "I will add deployment later!"'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
        type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
      - deploy:
        requires:
          - hold
